version: '3'
services:
  database:
    image: mysql:8.0.21
    # platform: linux/86_64  essa linha para mac
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: 'always'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup:/backup

volumes:
  mysql_data:
